/**
 * Audit action types organized by domain
 * Format: DOMAIN.ACTION (e.g., USERS.LIST, PAYMENTS.GET)
 */
export const AuditActions = {
  // Authentication & Users
  AUTH: {
    LOGIN: 'AUTH.LOGIN',
    LOGOUT: 'AUTH.LOGOUT',
    REGISTER: 'AUTH.REGISTER',
    REFRESH_TOKEN: 'AUTH.REFRESH_TOKEN',
  },
  USERS: {
    LIST: 'USERS.LIST',
    GET: 'USERS.GET',
    GET_BY_ID: 'USERS.GET_BY_ID',
    GET_ME: 'USERS.GET_ME',
    CREATE: 'USERS.CREATE',
    UPDATE: 'USERS.UPDATE',
    DELETE: 'USERS.DELETE',
  },

  // Merchants
  MERCHANTS: {
    LIST: 'MERCHANTS.LIST',
    GET: 'MERCHANTS.GET',
    GET_ME: 'MERCHANTS.GET_ME',
    CREATE: 'MERCHANTS.CREATE',
    UPDATE: 'MERCHANTS.UPDATE',
    DELETE: 'MERCHANTS.DELETE',
    GET_CARDS: 'MERCHANTS.GET_CARDS',
    GET_PAYMENT_LINK: 'MERCHANTS.GET_PAYMENT_LINK',
  },

  // Payments
  PAYMENTS: {
    LIST: 'PAYMENTS.LIST',
    GET: 'PAYMENTS.GET',
    GET_BY_ID: 'PAYMENTS.GET_BY_ID',
    GET_BY_SESSION: 'PAYMENTS.GET_BY_SESSION',
    GET_MERCHANT_PAYMENTS: 'PAYMENTS.GET_MERCHANT_PAYMENTS',
    GET_MERCHANT_STATS: 'PAYMENTS.GET_MERCHANT_STATS',
    INITIATE_STK: 'PAYMENTS.INITIATE_STK',
    VALIDATE_TOKEN: 'PAYMENTS.VALIDATE_TOKEN',
  },

  // NFC
  NFC: {
    LIST: 'NFC.LIST',
    GET: 'NFC.GET',
    GET_BY_ID: 'NFC.GET_BY_ID',
    DECODE: 'NFC.DECODE',
    CREATE: 'NFC.CREATE',
    UPDATE: 'NFC.UPDATE',
  },

  // Ledger
  LEDGER: {
    LIST_ENTRIES: 'LEDGER.LIST_ENTRIES',
    CREATE_ENTRIES: 'LEDGER.CREATE_ENTRIES',
    GET_BALANCE: 'LEDGER.GET_BALANCE',
  },

  // Notifications
  NOTIFICATIONS: {
    LIST: 'NOTIFICATIONS.LIST',
    SEND_SMS: 'NOTIFICATIONS.SEND_SMS',
    SEND_EMAIL: 'NOTIFICATIONS.SEND_EMAIL',
    SEND_PUSH: 'NOTIFICATIONS.SEND_PUSH',
  },

  // Webhooks
  WEBHOOKS: {
    LIST: 'WEBHOOKS.LIST',
    GET_BY_ID: 'WEBHOOKS.GET_BY_ID',
    DARAJA_CALLBACK: 'WEBHOOKS.DARAJA_CALLBACK',
    AFRICASTALKING_SMS: 'WEBHOOKS.AFRICASTALKING_SMS',
  },

  // Queues
  QUEUES: {
    LIST: 'QUEUES.LIST',
    GET: 'QUEUES.GET',
    GET_JOBS: 'QUEUES.GET_JOBS',
    GET_JOB: 'QUEUES.GET_JOB',
    RETRY_JOB: 'QUEUES.RETRY_JOB',
    REMOVE_JOB: 'QUEUES.REMOVE_JOB',
    CLEAN: 'QUEUES.CLEAN',
    PAUSE: 'QUEUES.PAUSE',
    RESUME: 'QUEUES.RESUME',
  },

  // Audit
  AUDIT: {
    LIST_LOGS: 'AUDIT.LIST_LOGS',
  },

  // Health & Metrics
  HEALTH: {
    CHECK: 'HEALTH.CHECK',
    READY: 'HEALTH.READY',
    METRICS: 'HEALTH.METRICS',
    VERSION: 'HEALTH.VERSION',
  },

  // QR Codes
  QR: {
    GENERATE: 'QR.GENERATE',
    GET: 'QR.GET',
    DOWNLOAD: 'QR.DOWNLOAD',
  },

  // PDF
  PDF: {
    GENERATE_CARD: 'PDF.GENERATE_CARD',
    GET_CARD: 'PDF.GET_CARD',
    DOWNLOAD: 'PDF.DOWNLOAD',
  },

  // Admin
  ADMIN: {
    DASHBOARD: 'ADMIN.DASHBOARD',
    RECENT_PAYMENTS: 'ADMIN.RECENT_PAYMENTS',
    MERCHANTS_OVERVIEW: 'ADMIN.MERCHANTS_OVERVIEW',
  },

  // Errors
  ERRORS: {
    VALIDATION: 'ERRORS.VALIDATION',
    NOT_FOUND: 'ERRORS.NOT_FOUND',
    UNAUTHORIZED: 'ERRORS.UNAUTHORIZED',
    FORBIDDEN: 'ERRORS.FORBIDDEN',
    INTERNAL: 'ERRORS.INTERNAL',
  },
} as const;

export type AuditActionType = string;
